### ISSUE TITLE
Add Osmosis types

### ISSUE THREAD

**Issue by jemrickrioux** [confio/cosmjs-types#27]
Hi guys,

I tried forking and adding Osmosis using the same logic as for wasmd and cosmos but it gets stuck saying that a proto has already been declared.

Could I get some more indications on how to do this, I would love contrbuting and adding more types :) 

I think my mistake lies in the fast that I created the third-party folder by copying the one in wasmd.

Thanks

**Comment by jemrickrioux** [comment]
@webmaster128 if you could give me a hand, it would be really appreciated.

**Comment by pyramation** [comment]
we can close this @webmaster128 

hey @jemrickrioux please see https://github.com/osmosis-labs/osmojs which has the types and also uses cosmjs
