### ISSUE TITLE
'Long' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by rishikhesh-cyD** [confio/cosmjs-types#41]
<img width="517" alt="Screenshot 2022-10-11 at 2 04 07 PM" src="https://user-images.githubusercontent.com/107479292/195040427-7eeefe21-b891-42b5-b9c9-d61d8319961e.png">

getting this error in all the places where Long is used in side the directory 
node_modules/cosmjs-types/tendermint

**Comment by rishikhesh-cyD** [comment]
@webmaster128 Can you help me with this

**Comment by webmaster128** [comment]
Do you have long or @types/long installed in your project? We use both in version 4 (not 5!) and this seems to work.

**Comment by rishikhesh-cyD** [comment]
Actually I installed osmojs, which has cosmjs/proto-signing as dependency and which inturn has dependency for cosmjs-types

**Comment by rishikhesh-cyD** [comment]
an example error :

 node_modules/cosmjs-types/cosmos/tx/signing/v1beta1/signing.d.ts:113:42 - error TS2702: 'Long' only refers to a type, but is being used as a namespace here.

113             sequence?: string | number | Long.Long | undef

**Comment by webmaster128** [comment]
`@types/long` makes this a namespace. So I guess there is something wrong with the dependency.

@pyramation do you have an idea what could be wrong with osmojs? Are you maintaining that?

**Comment by pyramation** [comment]
we had a similar issue in osmojs but used `import * as Long from 'long'` which solved the issue. When the typescript compiler started to error out from cosmjs-types, I didn't know how to fix that as it is a dependency. However, it could end up getting fixed after https://github.com/confio/cosmjs-types/issues/40 with the same fix I just deployed.

**Comment by rishikhesh-cyD** [comment]
@webmaster128 @pyramation What should i do now ?

**Comment by pyramation** [comment]
> @webmaster128 @pyramation What should i do now ?

I think you should leverage `ts-ignore` somewhere in your project.

**Comment by rishikhesh-cyD** [comment]
Thanks @pyramation @webmaster128 looking forward for the cosmjs update soon

**Comment by rishikhesh-cyD** [comment]
Thanks, @pyramation @webmaster128 looking forward for the cosm-js update soon

**Comment by webmaster128** [comment]
The latest release cosmjs-types 0.9.0 gets rid of long entirely. All 64 bit integers types use bigint now.
