### ISSUE TITLE
should this be 'string' ?

### ISSUE THREAD

**Issue by PFC-developer** [confio/cosmjs-types#53]
TallyParams currently returns Uint8Array
I'm guessing it should be a string.

https://github.com/confio/cosmjs-types/blob/68cf7a251832df100d8dba47d05d6036967b754c/src/cosmos/gov/v1beta1/gov.ts#L268

**Comment by webmaster128** [comment]
See https://github.com/cosmos/cosmos-sdk/issues/10863 and `decodeCosmosSdkDecFromProto` from `@cosmjs/stargate` for a decoder

**Comment by PFC-developer** [comment]
thx
