### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by happylolonly** [confio/cosmjs-types#65]
Maybe here better check as just `!value`?
We had a bug because value was undefined.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/18665326/234010403-71cf26d8-02e1-47c6-898d-0534bc2f1331.png">

https://github.com/confio/cosmjs-types/blob/main/src/cosmos/gov/v1beta1/gov.ts#L412

**Comment by webmaster128** [comment]
The field must be a string which is checked at compile time: https://github.com/confio/cosmjs-types/blob/main/src/cosmos/gov/v1beta1/gov.ts#L201
Using TypeScript fixes this, right? The entire CosmJS stack will not be very nice to you in case you provide arguments in the wrong type.

**Comment by happylolonly** [comment]
yes, seems TS would prevent this. we using 0.4.1 version, looks it wasn't type. will try to update in future

**Comment by webmaster128** [comment]
You mean cosmjs-types 0.4.1? There it is the same type: https://github.com/confio/cosmjs-types/blob/v0.4.1/src/cosmos/gov/v1beta1/gov.ts#L160

Is your app in TypeScript?

**Comment by happylolonly** [comment]
yes, sorry, was our issue. not specified body type

**Comment by happylolonly** [comment]
https://github.com/cybercongress/soft3.js/blob/main/src/signingcyberclient.ts#L767

added your types, now should validate correct
