### ISSUE TITLE
cosmos-sdk v0.45.16-ics-lsm-rc0 support

### ISSUE THREAD

**Issue by srph** [confio/cosmjs-types#73]
Hi all, I'm working on [Stride](https://stride.zone/)'s frontend, and we're looking to release LSM soon.

I was wondering if we can have support for [`v0.45.16-ics-lsm-rc0`](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.16-ics-lsm-rc0). I mostly need support for registry types like `MsgTokenizeShares` and `MsgRedeemTokenForShares`.

Currently as a workaround, I've made `cosmos-sdk` become a git submodule of `stridejs`, making it a direct part of the build, to make sure I have access to a registry that includes aforementioned transactions.

I'm not sure if this is the right place, but it seems that Stargate imports the proto encoders from this library.

If there's anything I can help with to make this happen, let me know :D

**Comment by webmaster128** [comment]
Since we already use a 0.47.x version here, I doubt we can easily apply this request. Can you get your types in an official 0.47 patch release?

**Comment by srph** [comment]
@webmaster128 Talked to my folks at Stride - seems like the types won't be upstreamed until Cosmos Hub itself upgrades to v47 which they mentioned may be in a few months.

We'll just keep the workaround for now and hopefully get things back to normal when the types are upstreamed. Thanks!
