### ISSUE TITLE
`protobufjs@^6` triggers override mistake

### ISSUE THREAD

**Issue by mhofman** [confio/cosmjs-types#78]
In Hardened JavaScript and similar environments the intrinsics are frozen for security.

`protobufjs` had an issue which triggered what is commonly known as the override mistake (using assignment to define a property which exists is unwritable in the prototype chain), in this case `constructor` of a custom `Error`.

That issue was fixed, but only as part of the `^7` major version. I'm not sure if there are breaking changes impacting this package, but updating `protobufjs` to the latest major would help projects using Hardened JS, like dapps building for the Agoric chain.

**Comment by webmaster128** [comment]
Thanks for bringing this up. I think we can even remove the protobufjs dependency entirely. See https://github.com/confio/cosmjs-types/pull/79

**Comment by webmaster128** [comment]
Done in #79

**Comment by mhofman** [comment]
Even better, thanks!!
