### ISSUE TITLE
Protobufjs vulnerability

### ISSUE THREAD

**Issue by hernan-clich** [confio/cosmjs-types#80]
A dependabot alert appeared in one of our repos related to protobufjs, this is the alert:

<img width="1275" alt="image" src="https://github.com/confio/cosmjs-types/assets/62221379/b2873ff0-c841-4bbd-a753-84922ee179a9">

After some traversing in our dependency tree I noticed that the latest version of `cosmjs-types` have it as a dependency.

<img width="432" alt="image" src="https://github.com/confio/cosmjs-types/assets/62221379/e4836f61-d3b0-40d2-8fc3-10eb998b3131">

I also saw that a PR was already merged to remove it from the `package.json` of the project so I would like to know when that change would be readily available so I can upgrade the version.

Thanks for your hard work!

**Comment by webmaster128** [comment]
I made a pre-release now and the integration is here: https://github.com/cosmos/cosmjs/pull/1484. Still a bit of work but once done, we can get a new CosmJS out with the dependency upgrade.

**Comment by webmaster128** [comment]
I think you can now just upgrader to version 6.11.4. At least this was recognized as a fixed version by GitHub in a different project I worked on. The version range was updated here: https://github.com/advisories/GHSA-h755-8qp9-cq85

Assuming this is done by using 6.11.4. In the meantime we try to get rid of the dependency, but this is likely not completely easy.
