### ISSUE TITLE
Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: 0: unknown proposal

### ISSUE THREAD

**Issue by PFC-developer** [confio/cosmjs-types#86]
hi.
i'm using 
*    "@cosmjs/cosmwasm-stargate": "^0.31.3",
*    "@keplr-wallet/types": "^0.12.38",
*   "cosmjs-types": "^0.9.0",
* (among other things)

I am creating the vote via
```
  const prop = BigInt(proposal_id);
        const vote = CosmosMsgVote.fromPartial({
          option,
          voter: account,
          proposalId: prop,
        });

        return [
          {
            value: vote,
            typeUrl: '/cosmos.gov.v1beta1.MsgVote',
          },
        ];
      }
```
which used to work, (and other transactions appear to work).
but when I call  SigningCosmWasmClient.simulate
it gives me 
```
rpc error: code = Unknown desc = failed to execute message; message index: 0: 0: unknown proposal
```
(the proposal exists on the chain).

The only 'strange' thing is when I print out the msg it shows up as 
```
proposalId: 18n, 
```
(note the 'n') .
any hints?

**Comment by webmaster128** [comment]
cosmjs-types ^0.9.0 is dsigned for the upcoming CosmJS 0.32. The current 0.31.x works with cosmjs-types ^0.8.0. I know this is not super convenient but maybe it helps to get closer to a solution.

**Comment by PFC-developer** [comment]
it does.. 
it had something to do with long/bigints.. switching to 'longs' (in 0.8.0 cured it)
