### ISSUE TITLE
cosmjs-types 0.9.0 doesn't compile

### ISSUE THREAD

**Issue by PFC-developer** [confio/cosmjs-types#92]
when I try to use it the following file stops vercel from building it.
removing the utf-8 character seems to make it happy locally.

```

Failed to compile.
16:28:22.092 |  
16:28:22.092 | ./node_modules/@cosmjs/encoding/build/utf8.d.ts:1:1
16:28:22.092 | Type error: File appears to be binary.
16:28:22.092 |  
16:28:22.093 | > 1 \| export declare function toUtf8(str: string): Uint8Array;
16:28:22.093 | \| ^
16:28:22.093 | 2 \| /**
16:28:22.093 | 3 \|  * Takes UTF-8 data and decodes it to a string.
16:28:22.093 | 4 \|  *
16:28:22.219 | Error: Command "yarn run build" exited with 1
16:28:22.843

<br class="Apple-interchange-newline">
```

**Comment by webmaster128** [comment]
Hey hey!

This looks like a bug in the tool that is executed at the build step. The linter? It probably checks for � to differentiate text from binary files but � is a valid unicode character. But it should be simple enough to change the doc comment to work around it.

**Comment by webmaster128** [comment]
Done in https://github.com/cosmos/cosmjs/pull/1570. This will be part of the next patch release of @cosmjs/encoding
